language: php

php:
  - 5.3
  - 5.4
  - 5.5

notifications:
    irc: "irc.freenode.org#kumbiaphp"
#    email:
#    - programador.manuel@gmail.com


env:
  - DB=mysql
#  - DB=pgsql
#  - DB=sqlite

before_script:
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database tests;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'create database IF NOT EXISTS tests;'; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE TABLE IF NOT EXISTS tests.usuario ( id int(11) NOT NULL DEFAULT 0, nombre  varchar(50) NOT NULL , email varchar(100) NOT NULL , activo bit(1) NULL DEFAULT b'1' , PRIMARY KEY (id) );'; fi"

script: phpunit --configuration tests/phpunit_$DB.xml --coverage-text --colors